project_id = "afrcagkprhtvvucukubf"

[functions.register-event]
verify_jwt = false

[functions.send-download-email]
verify_jwt = false

[functions.generate-og-image]
verify_jwt = true

[functions.translate-content]
verify_jwt = true

[functions.cleanup-orphaned-images]
verify_jwt = true

[functions.get-logo-base64]
verify_jwt = false

[functions.confirm-mautic-optin]
verify_jwt = false

[functions.upload-news-images]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = true

[functions.admin-update-user]
verify_jwt = true

[functions.admin-delete-user]
verify_jwt = true

[functions.generate-focus-keyword]
verify_jwt = true

[functions.generate-h1-headline]
verify_jwt = true

[functions.generate-intro-text]
verify_jwt = true

[functions.generate-seo-title]
verify_jwt = true

[functions.generate-seo-description]
verify_jwt = true

[functions.generate-internal-links]
verify_jwt = true

[functions.generate-external-links]
verify_jwt = true

[functions.suggest-content-links]
verify_jwt = true

[functions.generate-cluster-content]
verify_jwt = true

[functions.fetch-external-content]
verify_jwt = true

[functions.download-external-file]
verify_jwt = false

[functions.generate-fkw-content-suggestions]
verify_jwt = true

[functions.generate-h2-headlines]
verify_jwt = true

[functions.generate-h3-headlines]
verify_jwt = true
